// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice =
  | ConstructTourSlice
  | ChooseTourSlice
  | DescriptionSlice;

/**
 * Content for HomePage documents
 */
interface HomepageDocumentData {
  /**
   * Title field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *HomePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>
  /**
   * Meta Title field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *HomePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * HomePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    'homepage',
    Lang
  >;

/**
 * Content for Input documents
 */
interface InputDocumentData {
  /**
   * Label field in *Input*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: input.label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Name field in *Input*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: input.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Placeholder field in *Input*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: input.placeholder
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  placeholder: prismic.KeyTextField;

  /**
   * Pattern field in *Input*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: input.pattern
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pattern: prismic.KeyTextField;

  /**
   * Type field in *Input*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: input.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<'email' | 'password' | 'text' | 'tel'>;
}

/**
 * Input document from Prismic
 *
 * - **API ID**: `input`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type InputDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<InputDocumentData>, 'input', Lang>;

type PageDocumentDataSlicesSlice = DescriptionSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>
  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, 'page', Lang>;

/**
 * Item in *Select → Options*
 */
export interface SelectDocumentDataOptionsItem {
  /**
   * Value field in *Select → Options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: select.options[].value
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  value: prismic.KeyTextField;

  /**
   * Value label field in *Select → Options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: select.options[].value_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  value_label: prismic.KeyTextField;
}

/**
 * Content for Select documents
 */
interface SelectDocumentData {
  /**
   * Label field in *Select*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: select.label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Name field in *Select*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: select.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Default option field in *Select*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: select.default_option
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  default_option: prismic.KeyTextField;

  /**
   * Options field in *Select*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: select.options[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  options: prismic.GroupField<Simplify<SelectDocumentDataOptionsItem>>;
}

/**
 * Select document from Prismic
 *
 * - **API ID**: `select`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SelectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SelectDocumentData>, 'select', Lang>;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;

  /**
   * Phone number field in *Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.phone_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  phone_number: prismic.NumberField;

  /**
   * Phone label field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.phone_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_label: prismic.KeyTextField;

  /**
   * Instagram field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.instagram
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram: prismic.LinkField;

  /**
   * Facebook field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.facebook
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  facebook: prismic.LinkField;

  /**
   * Vkontakte field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.vkontakte
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  vkontakte: prismic.LinkField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    'settings',
    Lang
  >;

/**
 * Item in *Tours → Cards*
 */
export interface ToursDocumentDataCardsItem {
  /**
   * Image field in *Tours → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tours.cards[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image2x field in *Tours → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tours.cards[].image2x
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2x: prismic.ImageField<never>;

  /**
   * Title field in *Tours → Cards*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: tours.cards[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Price field in *Tours → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tours.cards[].price
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  price: prismic.RichTextField;

  /**
   * Link field in *Tours → Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: tours.cards[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Tours documents
 */
interface ToursDocumentData {
  /**
   * Name field in *Tours*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tours.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * IsCurrent field in *Tours*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: tours.iscurrent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  iscurrent: prismic.BooleanField;

  /**
   * Cards field in *Tours*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: tours.cards[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cards: prismic.GroupField<Simplify<ToursDocumentDataCardsItem>>;
}

/**
 * Tours document from Prismic
 *
 * - **API ID**: `tours`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ToursDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ToursDocumentData>, 'tours', Lang>;

export type AllDocumentTypes =
  | HomepageDocument
  | InputDocument
  | PageDocument
  | SelectDocument
  | SettingsDocument
  | ToursDocument;

/**
 * Primary content in *ChooseTour → Primary*
 */
export interface ChooseTourSliceDefaultPrimary {
  /**
   * Title field in *ChooseTour → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: choose_tour.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Primary content in *ChooseTour → Items*
 */
export interface ChooseTourSliceDefaultItem {
  /**
   * Tours field in *ChooseTour → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: choose_tour.items[].tours
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tours: prismic.ContentRelationshipField<'tours'>;
}

/**
 * Default variation for ChooseTour Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ChooseTourSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ChooseTourSliceDefaultPrimary>,
  Simplify<ChooseTourSliceDefaultItem>
>;

/**
 * Slice variation for *ChooseTour*
 */
type ChooseTourSliceVariation = ChooseTourSliceDefault;

/**
 * ChooseTour Shared Slice
 *
 * - **API ID**: `choose_tour`
 * - **Description**: ChooseTour
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ChooseTourSlice = prismic.SharedSlice<
  'choose_tour',
  ChooseTourSliceVariation
>;

/**
 * Primary content in *ConstructTour → Primary*
 */
export interface ConstructTourSliceDefaultPrimary {
  /**
   * Title field in *ConstructTour → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *ConstructTour → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Input_name label field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.input_name_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_name_label: prismic.KeyTextField;

  /**
   * Input_name id field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.input_name_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_name_id: prismic.KeyTextField;

  /**
   * Input_name placeholder field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.input_name_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_name_placeholder: prismic.KeyTextField;

  /**
   * Select label field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.select_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  select_label: prismic.KeyTextField;

  /**
   * Select id field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.select_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  select_id: prismic.KeyTextField;

  /**
   * Select default_option field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.select_default_option
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  select_default_option: prismic.KeyTextField;

  /**
   * Input_email label field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.input_email_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_email_label: prismic.KeyTextField;

  /**
   * Input_email id field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.input_email_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_email_id: prismic.KeyTextField;

  /**
   * Input_email placeholder field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.input_email_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_email_placeholder: prismic.KeyTextField;

  /**
   * Input_phone label field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.input_phone_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_phone_label: prismic.KeyTextField;

  /**
   * Input_phone id field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.input_phone_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_phone_id: prismic.KeyTextField;

  /**
   * Input_phone placeholder field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.input_phone_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_phone_placeholder: prismic.KeyTextField;

  /**
   * Input_datefrom label field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.input_datefrom_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_datefrom_label: prismic.KeyTextField;

  /**
   * Input_datefrom id field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.input_datefrom_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_datefrom_id: prismic.KeyTextField;

  /**
   * Input_datefrom placeholder field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.input_datefrom_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_datefrom_placeholder: prismic.KeyTextField;

  /**
   * Input_dateto label field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.input_dateto_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_dateto_label: prismic.KeyTextField;

  /**
   * Input_dateto id field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.input_dateto_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_dateto_id: prismic.KeyTextField;

  /**
   * Input_dateto placeholder field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.input_dateto_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_dateto_placeholder: prismic.KeyTextField;

  /**
   * Textarea label field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.textarea_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  textarea_label: prismic.KeyTextField;

  /**
   * Textarea id field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.textarea_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  textarea_id: prismic.KeyTextField;

  /**
   * Radio name field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.radio_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  radio_name: prismic.KeyTextField;

  /**
   * Radio legend field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.radio_legend
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  radio_legend: prismic.KeyTextField;

  /**
   * Radio id 1 field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.radio_id_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  radio_id_1: prismic.KeyTextField;

  /**
   * Radio value 1 field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.radio_value_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  radio_value_1: prismic.KeyTextField;

  /**
   * Radio label 1 field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.radio_label_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  radio_label_1: prismic.KeyTextField;

  /**
   * Radio id 2 field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.radio_id_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  radio_id_2: prismic.KeyTextField;

  /**
   * Radio value 2 field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.radio_value_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  radio_value_2: prismic.KeyTextField;

  /**
   * Radio label 2 field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.radio_label_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  radio_label_2: prismic.KeyTextField;

  /**
   * Checkbox hidden legend field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.checkbox_hidden_legend
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  checkbox_hidden_legend: prismic.KeyTextField;

  /**
   * Checkbox id field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.checkbox_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  checkbox_id: prismic.KeyTextField;

  /**
   * Checkbox name field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.checkbox_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  checkbox_name: prismic.KeyTextField;

  /**
   * Checkbox label field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.checkbox_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  checkbox_label: prismic.KeyTextField;

  /**
   * Checkbox link field in *ConstructTour → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.checkbox_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  checkbox_link: prismic.LinkField;

  /**
   * Checkbox link label field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.checkbox_link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  checkbox_link_label: prismic.KeyTextField;

  /**
   * Submit button label field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.submit_button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  submit_button_label: prismic.KeyTextField;

  /**
   * Reset button label field in *ConstructTour → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.primary.reset_button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  reset_button_label: prismic.KeyTextField;
}

/**
 * Primary content in *ConstructTour → Items*
 */
export interface ConstructTourSliceDefaultItem {
  /**
   * Select_option_name field in *ConstructTour → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.items[].select_option_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  select_option_name: prismic.KeyTextField;

  /**
   * Select_option_value field in *ConstructTour → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.items[].select_option_value
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  select_option_value: prismic.KeyTextField;

  /**
   * Select field in *ConstructTour → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.items[].select
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  select: prismic.ContentRelationshipField<'select'>;

  /**
   * Input field in *ConstructTour → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: construct_tour.items[].input
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  input: prismic.ContentRelationshipField<'input'>;
}

/**
 * Default variation for ConstructTour Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ConstructTourSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ConstructTourSliceDefaultPrimary>,
  Simplify<ConstructTourSliceDefaultItem>
>;

/**
 * Slice variation for *ConstructTour*
 */
type ConstructTourSliceVariation = ConstructTourSliceDefault;

/**
 * ConstructTour Shared Slice
 *
 * - **API ID**: `construct_tour`
 * - **Description**: ConstructTour
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ConstructTourSlice = prismic.SharedSlice<
  'construct_tour',
  ConstructTourSliceVariation
>;

/**
 * Primary content in *Description → Primary*
 */
export interface DescriptionSliceDefaultPrimary {
  /**
   * Title field in *Description → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: description.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Description → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: description.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button field in *Description → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: description.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField;

  /**
   * Button label field in *Description → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: description.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;
}

/**
 * Default variation for Description Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DescriptionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<DescriptionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Description → Primary*
 */
export interface DescriptionSliceWithoutButtonPrimary {
  /**
   * Title field in *Description → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: description.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description 1 field in *Description → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: description.primary.description_1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_1: prismic.RichTextField;

  /**
   * Description 2 field in *Description → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: description.primary.description_2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_2: prismic.RichTextField;

  /**
   * Description 3 field in *Description → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: description.primary.description_3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_3: prismic.RichTextField;
}

/**
 * Without button variation for Description Slice
 *
 * - **API ID**: `withoutButton`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DescriptionSliceWithoutButton = prismic.SharedSliceVariation<
  'withoutButton',
  Simplify<DescriptionSliceWithoutButtonPrimary>,
  never
>;

/**
 * Slice variation for *Description*
 */
type DescriptionSliceVariation =
  | DescriptionSliceDefault
  | DescriptionSliceWithoutButton;

/**
 * Description Shared Slice
 *
 * - **API ID**: `description`
 * - **Description**: Description
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DescriptionSlice = prismic.SharedSlice<
  'description',
  DescriptionSliceVariation
>;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      InputDocument,
      InputDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SelectDocument,
      SelectDocumentData,
      SelectDocumentDataOptionsItem,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      ToursDocument,
      ToursDocumentData,
      ToursDocumentDataCardsItem,
      AllDocumentTypes,
      ChooseTourSlice,
      ChooseTourSliceDefaultPrimary,
      ChooseTourSliceDefaultItem,
      ChooseTourSliceVariation,
      ChooseTourSliceDefault,
      ConstructTourSlice,
      ConstructTourSliceDefaultPrimary,
      ConstructTourSliceDefaultItem,
      ConstructTourSliceVariation,
      ConstructTourSliceDefault,
      DescriptionSlice,
      DescriptionSliceDefaultPrimary,
      DescriptionSliceWithoutButtonPrimary,
      DescriptionSliceVariation,
      DescriptionSliceDefault,
      DescriptionSliceWithoutButton,
    };
  }
}
