// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  choose_tour: dynamic(() => import('./ChooseTour')),
  construct_tour: dynamic(() => import('./ConstructTour')),
  description: dynamic(() => import('./Description')),
};
